version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: P0S7GR3SQ1
      DB_HOST: db
      DB_NAME: Incidentes
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P0S7GR3SQ1
      POSTGRES_DB: Incidentes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
